- name: install systemd-journal-remote
  apt:
    name: systemd-journal-remote
    state: present

- name: template /etc/systemd/journal-upload.conf
  template:
    src: templates/etc/systemd/journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart systemd-journal-upload

- name: template /etc/systemd/system/systemd-journal-upload.service
  template:
    src: templates/etc/systemd/system/systemd-journal-upload.service.j2
    dest: /etc/systemd/system/systemd-journal-upload.service 
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart systemd-journal-upload
